### PR TITLE
Update KitPro.php

### PR DESCRIPTION
**Pull request by legoboy0215**
Settings is for future.

### CODE REVIEW

**Comment by Glitchmaster-PE** [comment]
I was actually planning on something a little different for Kit management, thanks though :)

**Comment by legoboy0215** [comment]
Ok. I though maybe this can be settings like do you want to have instant armor or manual? I did not mean to have this as a kit se'ector... :)

**Comment by Glitchmaster-PE** [comment]
Ah, ok, I'll see if I end up adding this later on, want to get some work on kit config before I mess with anything else though :)

**Comment by legoboy0215** [comment]
:) Of course... This is your repo lol xD

**Pull request closed without merging**
